### ISSUE TITLE
uni1 hardcoded into includes\common.php

### ISSUE THREAD

**Issue by mrobaer** [Danter14/Xterium#1]
Lines 151, 156, 160, 162.

Admin page loads after install if uni1 is database name.  If database name is different, errors occur.

Message: SQL Error: Table 'uni2.uni1_banned' doesn't exist

Thank you for releasing this public and free!

**Comment by Danter14** [comment]
Yes to the only time the uni1_ works but will make sure you can put the name of table prefix you want

Thank you to follow the project

**Comment by mrobaer** [comment]
Yes, you are correct.  I will remain with uni1 database for simplicity.  Should I post all problems here, or do you have another way to communicate?

**Comment by Danter14** [comment]
best and post them here allows me to her properly follow my lead and solving problems
By wire 1 against bug
