### ISSUE TITLE
Language encode in register

### ISSUE THREAD

**Issue by joancefet** [Danter14/Xterium#15]
Hi, I am working in portuguese translation and give errors from encode because accentuation:
sorry for my bad english.

[15-Jul-2015 06:36:57] USER ERROR: "SQL Error: Incorrect string value: '\xE7\xE3o de...' for column 'message_text' at row 1Query Code: INSERT INTO uni1_messages SET 
	message_owner = 2, 
	message_sender = 1, 
	message_time = 1436953017, 
	message_type = 1, 
	message_from = 'Administrador', 
	message_subject = 'Bem-vindo', 
	message_text = 'Bem-vindo ao Stellar Wars! A primeira construção deverá ser uma planta de energia solar, porque a energia é necessária para a subsequente produção de matérias-primas. Para construí-la, clique no menu à esquerda, \"Edifícios\". Em seguida, procure o quarto edifício a partir do topo.  Lá tem a planta de energia: agora que já a construiu deve começar as minas de matérias-primas. Volte para o menu dos edifícios e construa uma mina de metal, em seguida, uma mina de cristal. A fim de ser capaz de construir naves, mas para isso precisa de ter construído o hangar. Poderá ver na página das tecnologias o que é necessário para que tenha acesso às varias naves, edifícios, e tecnologias.Se você tiver mais dúvidas, pode checar o guia do iniciante, nosso forum ou abrir um ticket no suporte.  A equipa do Stellar Wars deseja-lhe muito divertimento a explorar o universo!!', 
	message_unread = '1', 
	message_universe = '1';"
File: /home/stell530/public_html/beta7/includes/classes/class.Database.php | Line: 80
URL: http://beta7.stellarwars.net/index.php?page=vertify&i=1&k=1e87d4bddd1a74b87e2f8b28bd695090 | Version: V 1.0
Stack trace:
#0 /includes/GeneralFunctions.php(471): Database-&gt;query('INSERT INTO uni...')
#1 /includes/pages/login/ShowVertifyPage.class.php(100): SendSimpleMessage(2, 1, 1436953017, 1, 'Administrador', 'Bem-vindo', 'Bem-vindo ao St...')
#2 /includes/pages/login/ShowVertifyPage.class.php(110): ShowVertifyPage-&gt;_activeUser()
#3 /index.php(40): ShowVertifyPage-&gt;show()
#4 {main}

**Comment by penguin1969** [comment]
I am not an expert, but I think this is due to the symbols that are in the text being sent.
, \"Edifícios\" to be more specific

**Comment by joancefet** [comment]
The problem is "accentuation". But, how to solve?

**Comment by Qwatayean** [comment]
The problem is not any accentuation, instead the file is not running UTF8 no-BOM

**Comment by joancefet** [comment]
Olá Qwata, como eu resolvo isso?

**Comment by joancefet** [comment]
SOLVED! Thanks and sorry.
Resolvido! Obrigado e desculpe pelo meu erro. Salvei com outro encode no meu editor de código. =S

**Comment by Qwatayean** [comment]
Desculpe a demora da resposta. Quando ocorrer esse problema, deves ter nas propriedades "Guardar com ANSI, UTF 8 ou UTF 8 sem BOM", depende do programa que usas :)
