### ISSUE TITLE
English Language Corrections

### ISSUE THREAD

**Issue by mrobaer** [Danter14/Xterium#5]
In PUBLIC.PHP ... lines 185 & 186 were basically reversed in meaning.  Line 175 made no sense in English.  Changing it to PLAY like the registration button is logical.

Line 175: $LNG['popup_login_button']  = "Play";
Line 185; $LNG['main_navigation_menu_head2']	= "Sign Up";
Line 186: $LNG['main_navigation_menu_head3']	= "Sign In";

**Comment by Danter14** [comment]
thanks you
