### ISSUE TITLE
Treasure Event 

### ISSUE THREAD

**Issue by MrMD2** [Danter14/Xterium#6]
Treasure Hunt has started.
20 Inactive planets have big amounts of resources.
Search for it, and steal it.
Happy Hunting !!!

La chasse au tresor a commencer.
20 planets inactive sont rempli de resource.
Chercher les, et vider les tous.
Happy Hunting !!!

SchatzJagd Hat Begonnen
20 inaktiver Planeten, ist voll mit vielen Rohstoffen
Du musst ihn finden, und hol dir die Rohstoffe
Viel Spass beim Suchen !!!

---

Asteroid Event started
Every asteroid that you harvest will bring you resource. more details

Evenement asteroid a commencer
Chaque asteroid que tu harvest te raportera des resource. plus de details

Asteroid Ereignis begann 
Jeder Asteroiden, die Sie ernten werden Sie Ressource bringen. weitere Informationen

--

Friendly fleets landed on all your planets
Des vaisseaux allies ont atteris sur toutes vos planetes
Freundliche Flotten landen auf deinen Planeten

--

How to off this message?

**Comment by Danter14** [comment]
it is in the admin panel part cron to disable

**Comment by Qwatayean** [comment]
The crons are not working correctly. I'll build something on admin panel so this can work.

**Comment by Danter14** [comment]
ok thanks

**Comment by Qwatayean** [comment]
Asteroid Panel is added already. I'm going to check the treasures.
