### ISSUE TITLE
Spanish Translation 

### ISSUE THREAD

**Issue by oldcid** [Danter14/Xterium#8]
i can help with a Spanish Translation if u need it.

**Comment by Qwatayean** [comment]
We would like it

**Comment by Danter14** [comment]
thanks you

**Comment by oldcid** [comment]
I just started i have a question for you guys also where do i change the default language, already did with the commons.php and the class.lang.php  but still showing english when i acces my website  already clear the cache also tryed everithing but could not do it i just copied the (en) and started translating it and rename some files and creates the .cfg file, but i need to set the root language to (languague/es) insted of (language/en) i am new into this and i can help a lot with the proyect deaign css styles also thanks for you time lets do this togethe!

**Comment by oldcid** [comment]
I just started i have a question for you guys also where do i change the default language, already did with the commons.php and the class.lang.php  but still showing english when i acces my website  already clear the cache also tryed everithing but could not do it i just copied the (en) and started translating it and rename some files and creates the .cfg file, but i need to set the root language to (languague/es) insted of (language/en) i am new into this and i can help a lot with the proyect deaign css styles also thanks for you time lets do this togethe!

**Comment by Yolanda22** [comment]
UPDATE `uni1_config` SET `lang` = 'YOURLANGCODE'  WHERE `uni` = 1;

Here have you a simple Sql Code for change the default game Language

**Comment by oldcid** [comment]
the code its working actually but still not changing my default language any other tip?

**Comment by Qwatayean** [comment]
Hello. Sorry taking long. Did you deleted cache?

**Comment by oldcid** [comment]
Thats what i already said on top post yes i did clean the cahe still not working

**Comment by Qwatayean** [comment]
Can you send me the lang files if possible? So I can check if is any malfunction.

You have my email at my profile

**Comment by oldcid** [comment]
Yes i will, let me finish my translation first 50% done thanka for the answer and hope we. An solve it.

**Comment by Qwatayean** [comment]
Yes. I know what is the issue. Since lang/en is the default language on the game, you can't delete that folder, what you can do is insert Spanish files on en folder (with .cfg file) so the game thinks the default language is Spanish with English codename.

A good way to change the language code is searching on includes/classes/class.Lang.php

**Comment by oldcid** [comment]
Yes i can do that but is not the correct way to do it thats easy i just wonder how to change it for good if not when i have to set up english files i will have to use another folder name becouse en its going to be taken already it already change includes/classes/class.Lang.php

**Comment by Qwatayean** [comment]
Send me to email soon you have Spanish complete so I can add to code
