### ISSUE TITLE
Transport Mission Error

### ISSUE THREAD

**Issue by mrobaer** [Danter14/Xterium#9]
While attempting to transport resources to a colony of mine, I receive this error:

NOTICE
Message: Undefined variable: ACTUAL
File: /includes/pages/game/class.ShowFleetStep3Page.php
Line: 274
URL: http://127.0.0.1/Xterium-1.0/game.php?page=fleetStep3
PHP-Version: 5.6.8
PHP-API: apache2handler
MySQL-Cleint-Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
2Moons Version: V 1.0
Debug Backtrace:
#0 /includes/pages/game/class.ShowFleetStep3Page.php(274): errorHandler(8, 'Undefined varia...', 'D://WWW//Xterium-...', 274, Array)
#1 /game.php(65): ShowFleetStep3Page->show()
#2 {main}

Deploy mission is successful, no error messages.   There appears to be a bug in the PUSHING logic.  

Edit:  On further review, it probably is due to Admin having "-" points, which is not a number.

**Comment by Yolanda22** [comment]
Test this 
https://github.com/Danter14/Xterium/blob/master/includes/pages/game/class.ShowFleetStep3Page.php

**Comment by mrobaer** [comment]
It works :)
